### ISSUE TITLE
AR0134-mono

### ISSUE THREAD

**Issue by yiyongrobotics** [Razbotics/Cam-IMU-Sync#1]
Hi,
I triger it with 20Hz, but the output image quality is bad and the frequecy is not expected 20 Hz, only around 8 Hz, and the quality is really bad just like the pic below. I think it is caused by an incorrect cfg file. do you have some solutions?

**Comment by Razbotics** [comment]
The cfg file supplied in this repo is only for MT9V034 sensor. I hope so you are supplying your own cfg file for AR0134 sensor because the registers of both sensors may differ.

**Comment by Razbotics** [comment]
@gouyiyong
 Please let me know if you are facing any further issues. Otherwise you can close this issue.
