### ISSUE TITLE
VIO

### ISSUE THREAD

**Issue by yiyongrobotics** [Razbotics/Cam-IMU-Sync#2]
have you use px4 imu and camera sync，and test any VIO? how accurate is it?

**Comment by Razbotics** [comment]
@gouyiyong Yes I have been working on and testing recently. VIO needs some parameter tuning. I will let you know once I complete it.

**Comment by yiyongrobotics** [comment]
do you meet this issue, Arduino nano board data output suddenly stop and no any data in serial port?

**Comment by Razbotics** [comment]
If I am not wrong you are using MPU6050 right? In that case I wasnt to know, which library you are using. I did experienced this issue in past when I used MPU6050.

**Comment by yiyongrobotics** [comment]
> in

yes, I am using mpu 6050, how did you fix?

**Comment by Razbotics** [comment]
By reading across internet forums. I found that some said that it is a bug in mpu6050 i2c library and others say we need to add pull up resistors in INT pin and SCL SDA pin. I suggest you to try providing a pull up resistor in INT pin atleast.
